### ISSUE TITLE
export only personnal data from meter to sheet

### ISSUE THREAD

**Issue by cricou76** [tr-o/SwitchBot-Data-Logger-for-Google-Sheets#2]
Hello ! 
many thanks for the code provided
i'm a newbie  , but i just need to export data from my personnal meter (Temperature / Humidity) on a google sheet , without comparing from wheaterdatamap data
the goal is to create, later, web site to see dashboard of all temp/humidity reading the google sheet....
how can i do it ?

again thanks for your code !!
Cricou

**Comment by tr-o** [comment]
Hello Cricou,

Thank you for your comment, and I'm glad you found the code useful!

In the updated version 0.1.3, the OpenWeatherMap data is excluded by default. To use the code with only your personal meter data (SwitchBot devices), you don't need to make any changes to the writeDataToAllSheets() function. The OpenWeatherMap data fetching line is already commented out.

I hope this helps you.

Best regards,
